# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 372d65e4052ed03a76e447bec322d9867495a353a580b986118f424f5bf1211420da6231d9e8d41bb9193a4e52878984c77d2349c2fec6a66b0d19bd405c9d85

test:
  secret_key_base: 6db75d4e47c01b4ea287692c0a35ac40188a0580790c2b77e93869948fb741e7002d7c97829e63c44c1d8b867b1d14eef19d81b9aa36cca9066a493770dcef29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
